### ISSUE TITLE
Windows build request

### ISSUE THREAD

**Issue by MobiuSRIT** [sandsmark/borderlands3-save-editor#1]
https://ci.appveyor.com/project/sandsmark/borderlands3-save-editor/build/artifacts no longer hosts the windows zip.  Is that something you might have archived somewhere?  I've got a bugged mission and this project looks like one of the only ones that dealt with futzed missions at all.

I figured an issue might have been a better way to request versus a direct email in case anyone else came looking.
Cheers,
MobiuS

**Comment by MobiuSRIT** [comment]
disregard. i compiled source on linux to do what needed to be done.

**Comment by PhilPhonic** [comment]
@MobiuSRIT could you share those compilation results? I'm unable to compile it on my Linux box. Jumping from one error to the next (I'm completely unexperienced with cmake)

**Comment by MobiuSRIT** [comment]
@PhilPhonic I spooled an ubuntu vm and have already deleted it, so I can't recall what packages and versions I ended up installing to get the code to compile. I remember messing around with versioning for libprotobuf for a while (and one function was renamed, so I did end up editing some of the source code).  However, even after compiling, I needed to edit a mission, so I ended up using https://github.com/apocalyptech/bl3-cli-saveedit to export my character to a json file, edit, and reimport.  The procedure for which is noted in https://github.com/apocalyptech/bl3-cli-saveedit/issues/14.

**Comment by sandsmark** [comment]
sorry, don't monitor this repo too closely since I finished the game, but I can see if I can kick off a new build and upload the zip to the repo

**Comment by sandsmark** [comment]
updated the protobuf stuff (slow saturday), and spent the most time fighting appveyor (as one does, the point of CI systems is to slow down development speed after all).

so it should in theory support the latest save file format, but I haven't tested it.

I also uploaded a build here, for future reference or something: https://github.com/sandsmark/borderlands3-save-editor/releases/download/arbitrary-release-because-github-is-dumb/borderlands3-save-editor-1.0.132.2880e4a1.zip

**Comment by sandsmark** [comment]
looking at what you did to fix it with bl3-cli-saveedit, I _think_ it is safe to remove the `failed = true;` around line in MissionsTab.cpp to be able to edit missions which we don't have data or names for. But no guarantees.
